### ISSUE TITLE
Software Engineer / SRE

### ISSUE THREAD

**Issue by phozzy** [ory/jobs#12]
Hello!
I find your project very exciting!
I always payed attention to the question of single sign on (authentication and authorisation) in all projects I participated in. At 2012-2013 I even discussed with my friends the idea of starting a similar project. Unfortunately friends on mine did not find this idea worthy enough or probably I could not explain how demanded that type of projects can be. And nowadays we can see projects like yours, companies like auth0... Also I was not skilled enough to start that project alone, probably that even almost not possible to do alone ...
Well, actually for a skilled developer like @Firstyear it is feasible to start a similar project like https://github.com/Firstyear/kanidm , but he is a real expert in this domain.
I am also thinking about starting a similar hobby project. The reasons why I am not joining kanidm project are: first - I am not qualified enough :-) , second - I found that project quite monolith and not cloud native.
And that is why I find your project very attractive: it has requirement to be cloud native and use a separate application per a function. So I will be really happy to join your project!
As example of my work I can show my recent project about containerised deployment of FreeIPA:
https://42zy.wordpress.com/2019/12/01/containerised-idm-deployment/
https://github.com/phozzy/freeipa-in-podman

I would like to receive any type of response, even if will be unpleasant one.

**Comment by Firstyear** [comment]
Hi there,

I'm going to respond to this here, but I'll just say I'm not sure if I'm the target of the comment/question, or if this is intended for ory - I think it's intended for ory though :) 

> Hello!
> I find your project very exciting!
> I always payed attention to the question of single sign on (authentication and authorisation) in all projects I participated in. At 2012-2013 I even discussed with my friends the idea of starting a similar project. Unfortunately friends on mine did not find this idea worthy enough or probably I could not explain how demanded that type of projects can be. And nowadays we can see projects like yours, companies like auth0... Also I was not skilled enough to start that project alone, probably that even almost not possible to do alone ...
> Well, actually for a skilled developer like @Firstyear it is feasible to start a similar project like https://github.com/Firstyear/kanidm , but he is a real expert in this domain.

I appreciate the compliment here! Thanks! I'll just say though, that I remember many years ago sitting on the floor with my laptop, unable to setup a single LDAP server, so now to be considered an expert is something I thought I would never achieve. But I also think that it shows that everyone starts somewhere, and you have the capability to be an expert as well. Kanidm certainly I think is my ... 4th (?) attempt at an IDM project, and so far it's the most successful one :)

> I am also thinking about starting a similar hobby project. The reasons why I am not joining kanidm project are: first - I am not qualified enough :-) , second - I found that project quite monolith and not cloud native.

You are qualified enough, I'm happy for anyone to contribute, and I'll help support as much as possible in the process.

With regard to "not cloud native", I think I don't have a good understanding of what cloud native is in this context. I chose to make Kanidm a single server binary because it allows detailed profiling of operations, it helps to constrain security layers (rather than having intermediate connections between parts), and because after my work on FreeIPA I saw it as being extremely fragile for all it's moving parts that need to be perfectly coordinated. I took great inspiration from Active Directory and Samba 4, so choosing a single binary stack aids developers in setting up an environment with minimal effort and resources and isolating issues/debugging. 

For me cloud native implies separation of concern (auth, sql, webserver ...) rather than splitting these into sub components (auth having multiple parts, or the webserver having a different fileserver to it's http server). It also means "easy to coordinate/automate" and that's certainly a strong goal of Kanidm to "just work", but I will admit that some of these ideas still do live in my head (replication for one).

> And that is why I find your project very attractive: it has requirement to be cloud native and use a separate application per a function. So I will be really happy to join your project!
> As example of my work I can show my recent project about containerised deployment of FreeIPA:
> https://42zy.wordpress.com/2019/12/01/containerised-idm-deployment/
> https://github.com/phozzy/freeipa-in-podman
> 
> I would like to receive any type of response, even if will be unpleasant one.

I wish you all the luck in this, and I hope that you receive a constructive response. 

For my own contribution, @phozzy has been an active member of the FreeIPA users group and I distinctly remember helping them with their efforts for FreeRADIUS and FreeIPA integration. They have always asked constructive, quality technical questions, and I consider them a valuable member of the LDAP community who wants to learn and improve. 

Good luck!

**Comment by aeneasr** [comment]
Thank you both! @phozzy if you reach out to jobs@ory.sh we can figure out a time to do an introductory call (so this here doesn't get flooded with scheduling) :)

@firstyear great to see that we're not the only project tackling identity with modern programming languages like Rust and a fresh approach! It's also great to see that you're trying to cover the full spectrum - from permissions, to template engines/ui, oauth2, mfa, pam, radius, ... - Tackling each problem on its own is already very ambitious steep learning curves and complex problem domains and solutions. If you ever feel like joining or contributing to another open source project, https://github.com/ory/kratos might be in your ballpark. While still under very active development and an unreleased status, it appears to be along the lines of what we all imagine a modern, open, scalable, identity infrastruture should look like.

Regarding cloud native, what most people mean by that: http://12factor.net

Cloud native nowadays is just a buzzword being abused by mostly bs marketing. For real devs, it means usually designing along the 12 factors, solving specific problem domains very well (vs "fullstack" mega projects) and with easy integration with existing systems, and in ways where deploying and operating the software on Kubernetes is an absolute no-brainer.

Hope this helps, and thank you both for your interest!

**Comment by Firstyear** [comment]
Thanks @aeneasr, I appreciate the detailed response. I look forward to having a look at kratos to gain some inspiration and ideas. I've also checked 12factor.net now and it was interesting - I have some work to do to improve logging and administration but I think otherwise Kanidm is in good shape for it :) 

It does help, and I appreciate your thoughtful answer and your own interest and passion in the space. I look forward to seeing how your own projects continue to progress too! If I have further questions about Kratos, what's the best way to ask these? Open an issue or some other means of communication? 

Thanks!

**Comment by aeneasr** [comment]
> It does help, and I appreciate your thoughtful answer and your own interest and passion in the space. I look forward to seeing how your own projects continue to progress too! If I have further questions about Kratos, what's the best way to ask these? Open an issue or some other means of communication?

Yes, just head over to the GH repo for kratos. We also have chatrooms, and a community forum for more generic questions.

**Comment by phozzy** [comment]
@aeneasr I sent an email to jobs@ory.sh and will close this issue.
